"""Provider-neutral contracts for future ULTRON capabilities.

Implementations belong server-side and must enforce authorization, audit logging,
and explicit data-retention policy before they are exposed via HTTP routes.
"""
from typing import Any, Protocol
from pydantic import BaseModel, Field


class ToolDefinition(BaseModel):
    name: str
    description: str
    input_schema: dict[str, Any]
    output_schema: dict[str, Any]
    permission_level: str = Field(description="read, write, or destructive")


class AIService(Protocol):
    async def respond(self, user_id: str, message: str) -> str: ...


class ConversationService(Protocol): ...
class MemoryService(Protocol): ...
class VisionService(Protocol): ...
class VoiceService(Protocol): ...
class ResearchService(Protocol): ...
class FileService(Protocol): ...
class CodeService(Protocol): ...
class DataAnalysisService(Protocol): ...
class AutomationService(Protocol): ...
class NotificationService(Protocol): ...
class ProjectService(Protocol): ...


class ToolService(Protocol):
    async def list_tools(self) -> list[ToolDefinition]: ...
